### ISSUE TITLE
"error_description":"AADSTS50027: JWT token is invalid or malformed

### ISSUE THREAD

**Issue by gregnottage** [FriedrichWeinmann/MiniGraph#4]
Hi Fred,

I'm getting an issue with the v1.0.2 module:

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\minigraph\1.0.2\MiniGraph.psm1:129 char:4
+             $outBytes = $Certificate.PrivateKey.SignData($inBytes, $A ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "ToBase64String" with "1" argument(s): "Value cannot be null.
Parameter name: inArray"
At C:\Program Files\WindowsPowerShell\Modules\minigraph\1.0.2\MiniGraph.psm1:130 char:4
+             [convert]::ToBase64String($outBytes)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Invoke-RestMethod : {"error":"invalid_request","error_description":"AADSTS50027: JWT token is invalid or malformed.\r\nTrace ID: d04f63eb-cdd1-4164-936e-675267d91700\r\nCorrelation ID: 6dc79eec-a7b1-4c26-99ed-cea9340accd3\r\nTimestamp:
2021-12-02 15:58:24Z","error_codes":[50027],"timestamp":"2021-12-02
15:58:24Z","trace_id":"d04f63eb-cdd1-4164-936e-675267d91700","correlation_id":"6dc79eec-a7b1-4c26-99ed-cea9340accd3","error_uri":"https://login.microsoftonline.com/error?code=50027"}
At C:\Program Files\WindowsPowerShell\Modules\minigraph\1.0.2\MiniGraph.psm1:203 char:25
+ ... pt:token = (Invoke-RestMethod -Uri $uri -Method Post -Body $body -Hea ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Please can you take a look when you have a moment, thanks Greg.

**Comment by FriedrichWeinmann** [comment]
Argh, sorry about the late response Greg :(
This would be the expected error when the private key is missing / inaccessible on the specified certificate.
Adding better error handling to the next iteration

**Comment by FriedrichWeinmann** [comment]
Alright, updated to version 1.1.4
Includes not only better error handling, it also is better at handling private keys, so if your cert should have included a private key, it should now work with the latest version.
Would you mind verifying?
